### ISSUE TITLE
Limit Gauge broken after editing save

### ISSUE THREAD

**Issue by KusanagiShiro** [sithlord48/blackchocobo#1]
V. 1.9.83 works but the limit gauge breaks even after editing the save without...IWITHOUT changing the limit bar.

**Comment by sithlord48** [comment]
Since I am unable to reproduce this with 1.9.83 or trunk please tell me, 
What Bundle did you download from the web page?
What Version of FF7 ?
What changes you did make to your save?

**Comment by KusanagiShiro** [comment]
I downloaded the latest from Steam. The Windiws version of BC. And the standard all items, eight sets of Master Materia, eight sets of Mega All and HP/MP/EXP Plus mastered and Enemy Skill Materia to make use of Big Guard. 

I also added a Gold Chocobo named Boco in loving tribute to FFV.
