### ISSUE TITLE
Masamune can't be equipped properly

### ISSUE THREAD

**Issue by ErionAiretam** [sithlord48/blackchocobo#10]
Replacing a character by Sephiroth seems to allow us to select Masamune as a weapon, but actually uses the last selected weapon of the replaced character
![Masamune](https://user-images.githubusercontent.com/45392070/59152207-def9db00-8a3f-11e9-8a0e-32f876af43ff.png)
.

**Comment by ErionAiretam** [comment]
Or maybe I'm editing a Vincent with a Sephiroth's picture. In this case, the bug is that the weapons list shouldn't have been replaced by Masamune.

**Comment by sithlord48** [comment]
You are expected to change weapons after you change a characters IDs.
