### ISSUE TITLE
Build for armhf (Raspberry Pi)

### ISSUE THREAD

**Issue by BioHazard1282** [sithlord48/blackchocobo#16]
So, I downloaded the .appimage and didn't realize it's for amd/arm64 archs. I'm on Raspberry Pi OS with RetroPie installed on a Raspberry Pi 3B.

I'd like to use this, but I don't have arm64. I noticed a recent build 5 days ago, and I am wondering if there is a build for armhf. 

(This is very much needed, since I'm in a very sticky situation in FF7 where I am about to leave the Gi Cave, but there is one battle in the way for me to make it to safety, and I don't have enough health or MP. :( )

If there isn't one for armhf, is it possible if you can make one (or possibly installable as a .deb package?)?

**Comment by sithlord48** [comment]
There is currently no CI setup for arm. you can build on arm fine i have built for my PBP (aarm64). Its fairly easy to build yourself just follow the [.travis.ym ](https://github.com/sithlord48/blackchocobo/blob/master/.travis.yml) file the travis instance is running ubuntu xenial so it should be very similar to whats running on your pi.

**Comment by sithlord48** [comment]
Having a CI that builds an Appimage for armf and aarm64 would be very useful. Anyone with the time is encouraged to make a PR.

**Comment by sithlord48** [comment]
Small update on this .I have moved to github actions and have some basic armhf builds for debian bullseye
 (it has to be bullseye for qt 5.15) 
This is done on the [ff7tk](https://www.github.com/sithlord48/ff7tk) repo. Please try downloading this [artifact](https://github.com/sithlord48/ff7tk/suites/4905097940/artifacts/141125994) inside you will find both a tarball and a debian file for ff7tk please try to run the ff7tkWidgetGallery on your pi and let me know if that works out . You can try the debian file also . If these are working i should be able to release similar for blackchocobo. (still looking into appimage for non x86 based linux)

**Comment by sithlord48** [comment]
Hello an update on this

If your running `ubuntu-22.04` on your pi. You should be able to use the debian files that are now built to install them you will need to first install [libff7tk](https://github.com/sithlord48/ff7tk/releases/tag/continuous) Then you can try the newest [continuous](https://github.com/sithlord48/blackchocobo/releases) Release and please report back.

 If you are running `arch` or `manjaro` you can install both libff7tk and blackchocobo from the AUR  (or the -git version for continuous release)

For other distros you should have the Qt6 dev packages and zlib dev packages, git, cmake and then you can build

ff7tk 
 1. git clone https://github.com/sithlord48/ff7tk.git
 2. cmake -Sff7tk -Bbuild -DCMAKE_INSTALL_PREFIX=/usr
 3. cmake --build build
 4. sudo cmake --install build

and Black chocobo 
 1. git clone https://github.com/sithlord48/blackchocobo.git
 2. cmake -S. -Bbuild -DCMAKE_INSTALL_PREFIX=/usr
 3. cmake --build build
 4. sudo cmake --install build
 
That should work on any disto
