### ISSUE TITLE
Incompatible with M1 Macbook

### ISSUE THREAD

**Issue by VanillaEssence** [sithlord48/blackchocobo#17]
Appears not to work on M1 Mac. Begins to launch but becomes unresponsive/infinite beachball.

Problem occurred on Macbook Air M1, Big Sur 11.2

**Comment by sithlord48** [comment]
This will be addressed in time. 
Qt needs to support Mac os on M1 and I also need Support in the CI systems to build for it. 

The current mac binary is for x86_64 mac os

**Comment by sithlord48** [comment]
expect the first build ti fail ff7tk is not ready yet build will a restart after ff7tk builds its universal libs
