### ISSUE TITLE
[Feature] Add support for compressed SRM files

### ISSUE THREAD

**Issue by Danixu** [sithlord48/blackchocobo#21]
Hello,

Playing with your program and Recalbox, I have noticed that it is not compatible with the compressed SRM format. This is the default option in RetroArch 1.8.5 and up, so this make impossible to open that files using this program until you deactivate the savegame compression, which can be a bit annoying, and even dangerous because can be activated again if not done correctly and will replace the savegame.

To avoid to be playing with the advanced options of the RetroArch program, will be nice to add compatibility with compressed SRM files.

I have created an example program which is able to compress and decompress SRM files, so maybe will help you with this feature:

https://github.com/Danixu/srm-compressor

I am using the RetroArch source files directly, which is a bit coarse, but is working... 😅 

Thanks!

**Comment by sithlord48** [comment]
Thanks for this report.  
This is an issue for [ff7tk](https://github.com/sithlord48/ff7tk)

Please use This issue https://github.com/sithlord48/ff7tk/issues/63 to track further.
