### ISSUE TITLE
File only shows one character (Cloud) when loaded on a mac

### ISSUE THREAD

**Issue by vinnybad** [sithlord48/blackchocobo#3]
Hello --

The editor shows only cloud.  Also when opening the file, an incorrectly sized modal or screen shows up.  Hitting escape proceeds forward but doesn't load all party member information.  

Example file: 
[ff7-save01.ff7.zip](https://github.com/sithlord48/blackchocobo/files/196067/ff7-save01.ff7.zip)

Also a readme - contribute section would be helpful.  Time permitting, I'd like to take a look at how this was implemented.  Thanks!

**Comment by sithlord48** [comment]
i don't have access to a mac to check this atm . i will do so later on .. the file seams correct here on my linux machine.

"Also a readme - contribute section would be helpful. Time permitting," "
we could always use help documenting and getting all our stuff moved over to github 

" I'd like to take a look at how this was implemented. Thanks!"

the code is well commented most of stuff belongs to the ff7tk you can find documents here
http://blackchocobo.com/ff7tk/index.html
for example your "issue" is most likely from one of these 3 ff7tk items
FF7Save - (http://blackchocobo.com/ff7tk/class_f_f7_save.html)
FF7CHAR - (http://blackchocobo.com/ff7tk/struct_f_f7_c_h_a_r.html)
SlotPreview (http://blackchocobo.com/ff7tk/class_slot_preview.html)

**Comment by sithlord48** [comment]
also can you post a screen shot of what your seeing on your machine .

**Comment by sithlord48** [comment]
I have checked on my mac and the save preview and save seam to be fine . i see all characters in your party  (os 10.9)

**Comment by vinnybad** [comment]
Here's an animated gif showing what I'm seeing:

You'll see a narrow window or alert with what looks like a button at the bottom shows up.  Tapping on the button seems to open the 'open file' dialog again.  I hit 'escape' and the file I had asked to open initially was opened.  

![b](https://cloud.githubusercontent.com/assets/81403/14163906/f06e072e-f6bf-11e5-8c45-31f694f3af90.gif)

**Comment by sithlord48** [comment]
thats it very unusual... let me see if i can get access to another mac to test more

**Comment by vinnybad** [comment]
If it helps, I can pair with you online to help resolve this issue.

On Thu, Mar 31, 2016 at 8:37 AM, sithlord48 <notifications@github.com>
wrote:

> thats it very unusual... let me see if i can get access to another mac to
> test more
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sithlord48/blackchocobo/issues/3#issuecomment-203939802>
>



-- 
Thanks,
Vinny

**Comment by sithlord48** [comment]
it seams like the bundle is missing a qt part .  
We don't have many users or any contriubters who are using Mac Os so testing on this platform is minimum . I would welcome any help from people using Mac OS!

**Comment by vinnybad** [comment]
Hello -- do you have a newer binary with the missing qt part?  I am available to help test this change if needed.  Thanks!

**Comment by sithlord48** [comment]
no i have not built any newer mac binaries, nor have i had anytime to debug the issue since mac os is difficult for me to work in as i dont have direct access to a machine running mac os . To build you will need qt creator and gcc (and openssl if you want to try to sign ps3 saves)

**Comment by ricardocolonia** [comment]
I have the exact same issue, i have tried in OSX 10.9 and 10.11, no changes. What can i do to help solve this problem, i can test, but i have no programming skills

**Comment by sithlord48** [comment]
i have checked the bundle and all the Qt parts seam to be in place. On the machine where it built it runs correctly and everything displays as it should.  
I have made a new bundle for mac os Please try the new file and report back 

https://github.com/sithlord48/blackchocobo/releases/download/v1.9.90/Black_Chocobo-1.9.90_mac.zip

**Comment by ricardocolonia** [comment]
Nothing, same result. Could be that the machine you are working has some sort of plugin needed for Black Chocobo to run properly? Maybe Xcode is required? Just thinking outside the box here.

Thanks



On Apr 17, 2016, at 7:37, sithlord48 <notifications@github.com<mailto:notifications@github.com>> wrote:


i have checked the bundle and all the Qt parts seam to be in place. On the machine where it built it runs correctly and everything displays as it should.

I have made a new bundle for mac os Please try the new file and report back

https://github.com/sithlord48/blackchocobo/releases/download/v1.9.90/Black_Chocobo-1.9.90_mac.zip

**Comment by vinnybad** [comment]
> I remember when writing Java swing UIs, I had to size the window properly after it appeared. Is it possible that the window needs to be resized properly when showing the additional dialog or screen? 

Perhaps we can release a build to manually resize the window to a fixed size if we are dynamically calculating that size and see if that fixes it?

**Comment by sithlord48** [comment]
The dialog works correct on other oses including the Mac I build the Mac version with. I'm not sure why the dialog is missing thigs but it has to be a dependent libary of something missing . I will try later to run macdeployqt to DMG file .I ran otool to check the libs needed and they all seam to point to ones in the bundle. When I get a chance I'll see if o can deploy another way and force bundled components . I would be willing to bet if you DL and install at the dialog will function correctly.

**Comment by vinnybad** [comment]
Ok sounds good, thank you for looking into this!

**Comment by ricardocolonia** [comment]
I Will try any solution you deploy and report back the results, just give me a heads up.

Thanks

Enviado desde mi iPhone

El 17/04/2016, a las 12:25 p.m., sithlord48 <notifications@github.com<mailto:notifications@github.com>> escribi?:


The dialog works correct on other oses including the Mac I build the Mac version with. I'm not sure why the dialog is missing thigs but it has to be a dependent libary of something missing . I will try later to run macdeployqt to DMG file .I ran otool to check the libs needed and they all seam to point to ones in the bundle. When I get a chance I'll see if o can deploy another way and force bundled components . I would be willing to bet if you DL and install at the dialog will function correctly.

-

**Comment by sithlord48** [comment]
Some news on this.. I seam to have installed two different copies of qt on the mac im building/packing with. This could be part of the problem as they are both the same version (5.5.1) one is installed with the qt package and the other with homebrew . I've removed both and Will install qt 5.6 (now that its out) and try to build / deploy again.

**Comment by ricardocolonia** [comment]
Great! Let us know when you have the download link!




Enviado desde mi iPhone

El 24/04/2016, a las 8:48 p.m., sithlord48 <notifications@github.com<mailto:notifications@github.com>> escribi?:


Some news on this.. I seam to have installed two different copies of qt on the mac im building/packing with. This could be part of the problem as they are both the same version (5.5.1) one is installed with the qt package and the other with homebrew . I've removed both and Will install qt 5.6 (now that its out) and try to build / deploy again.

-

**Comment by sithlord48** [comment]
round 3 fight. i mean here is another bundle i don't see any dialog but i have very broken GL on this "mac". let me know how it works for y'all
[Black_Chocobo.zip](https://github.com/sithlord48/blackchocobo/files/236627/Black_Chocobo.zip)

**Comment by kepps2113** [comment]
Sithlord, I'm having this issue as well.  The one from April 26th doesn't load any windows at all and doesn't have any menu options - only the "Black Chocobo".  I downloaded 1.8, and it doesn't have those issues - but of course it can't load save files from emulators...

**Comment by sithlord48** [comment]
yeah im really not sure why this happens . if you install qtcreator and build black chocobo it works just fine on mac os.

**Comment by Buzhanin** [comment]
I had this issue on Debian 9 with KDE desktop
Fix diff : [fix.zip](https://github.com/sithlord48/blackchocobo/files/1437892/fix.zip)

It's just a regular type casting mistake that 
makes scale = 0 if logicalDpiX() returns value less than 96
I'm not sure if mac users experience the issue for the same reason, but who knows? :)

**Comment by sithlord48** [comment]
Thanks.

**Comment by sithlord48** [comment]
Im Fairly sure this is a packaging issue. If anyone with mac os can report if the autogen builds have this issue. https://github.com/sithlord48/blackchocobo/releases/continuous

**Comment by Ickerday** [comment]
Continuous build still has the same issue.

**Comment by peeweeyoshi** [comment]
This worked for me;

Go to preferences, set "scale widgets by" to 2.0, close and reopen the program and should work like it does on PC.
