### ISSUE TITLE
Load file cannot be closed.

### ISSUE THREAD

**Issue by DLPB2** [sithlord48/blackchocobo#7]
Once the "Select a slot" window is placed up - it is show modal only. And the Close X is greyed out.  This means you are forced to use "Load another file" in order to go back to the main window.

**Comment by sithlord48** [comment]
You don't just accidentally disable the close event on a dialog this is intended. If you load a file with multipal slots you must pick one for file loading to be successful.

**Comment by DLPB2** [comment]
The problem is opening a file and deciding you no longer want to.  I've done it a few times.,
