### ISSUE TITLE
Settings hext file for 7th Heaven

### ISSUE THREAD

**Issue by PureMindGames** [sithlord48/blackchocobo#73]
Is it possible to create a hext edit file for 7th Heaven for 'Game Options'? For instance if I wanted the cursor to always be 'Memory'? by default?

**Comment by sithlord48** [comment]
What does this have todo with blackchocobo ?
You want to use memory by default then you need to edit the stock save in your exe to have that in the default map. Both are not in the scope of this project

**Comment by PureMindGames** [comment]
It was more of question than anything, but the only options are 'Bug Report' or 'Feature Request' and this was the only program I could think of that lets you set the options prior to starting a game. Sorry for bothering you.

**Comment by sithlord48** [comment]
> It was more of question than anything, but the only options are 'Bug Report' or 'Feature Request' and this was the only program I could think of that lets you set the options prior to starting a game. Sorry for bothering you.

You will have better luck opening an issue on their repo 
https://github.com/tsunamods-codes/7th-Heaven
