### ISSUE TITLE
Cloud dissapears!

### ISSUE THREAD

**Issue by RainRuru** [sithlord48/blackchocobo#75]
**NOTICE**
Your bug maybe part of [ff7tk](https://www.github.com/sithlord48/ff7tk) if so it will be moved to the ff7tk issue tracked and linked. 

**Describe the bug**
When removing Cloud from the party with the PHS, the game removes him from all scenes that aren't the overworld for some reason.
This persists after re-adding him to the party and the only way I can interact with anything now is to have Tifa or Cid in the party so their models show up instead.

**To Reproduce**
1. Go to 'Other' - 'PHS Manager' and allow Cloud to be removed.
2. Click on 'Save'
3. Launch the game
4. If you remove Cloud and enter an area like Costa del Sol you'll be invisible or you'll be Tifa, Cid, or apparently Barret too depending on who is in the party and where you are.

**Expected behavior**

I expected to be able to freely swap them around and as long as Cloud was in the party, he would be visible and fully functional.

**Screenshots**
![Screenshot 2024-03-16 015501](https://github.com/sithlord48/blackchocobo/assets/140693565/674615d5-21ea-4e3f-b523-657bda684822)
![Screenshot 2024-03-16 015608](https://github.com/sithlord48/blackchocobo/assets/140693565/abcdd484-13bf-422b-90af-4fe37f5bfbba)

**System Info (please complete the following information):**
 - OS: PC
 - Version: Steam

**Additional context**

**Comment by sithlord48** [comment]
Welcome to what happens when you do things the games does not expect.
