### ISSUE TITLE
My save files disappear after using black chocobo editor

### ISSUE THREAD

**Issue by cyberazi** [sithlord48/blackchocobo#78]
**NOTICE**
Your bug maybe part of [ff7tk](https://www.github.com/sithlord48/ff7tk) if so it will be moved to the ff7tk issue tracked and linked. 

**Describe the bug**
i lots my savefiles after editing my savefiles i was not able to continue m game after i use the savegame editor

**To Reproduce**
1. played the game to a certain event - in this case after  Don Corleone and saved 
2. tried to edit the savegame to add materias at full levels

**Expected behavior**
Was homping to get at least 3 copies of each materia in the materia list ingame where i can assign them accordingly but my saves dissapeared and i am unable to contnue the game

**Screenshots**

**System Info (please complete the following information):**
 - OS: windows 11

**Additional context**

**Comment by sithlord48** [comment]
There is nothing of use for me to help you in this report as is.

1. What Version of FF7 are you playing 
2. Where did you save the files ?

**Comment by cyberazi** [comment]
What Version of FF7 are you playing
Steam version . Build ID:115956 V1.09
Where did you save the files ?
\Document|Square Enix\FINAL FANTASY VII Steam\user_xxxxxxxxx\
[user_38150023 - 11may24 1322H.zip](https://github.com/sithlord48/blackchocobo/files/15308052/user_38150023.-.11may24.1322H.zip)
Added my backed up saved games afetr edit the save games are gone i dad to quit and restart then coper over my backed up saved games for restore my games progress

**Comment by sithlord48** [comment]
You never said what version of blackchocobo you are using. If its not the newest continuous release please try with that.

Looking at your archive I see this is your user  folder from either steam or pc2012 (square store release). 

The steam (and pc2012) versions require an additional file `metadata.xml`. That file is used to control what is synced to the cloud saves. If its not correct the offending save is removed. To work with this in blackchocobo when you save a file into a path with a metadata.xml file it should be updated. You also have to use the proper save names `save00.ff7,  save01.ff7 ...`. Can you check that the metadata.xml files is being changed when you update your save00.ff7 file in the steam save path.

**Comment by sithlord48** [comment]
Finally got my steam copy working and i can not recreate this issue. 
 
- Make sure you have closed not only the game but its launcher as well. the launcher when it closes maybe messing up your metadata.xml

**Comment by cyberazi** [comment]
the Black chocobo  version 1.14, ff7tk:0.83.2.0 Qt:6.4.2
i am gonna try again to check if it works

**Comment by sithlord48** [comment]
the current version of black chocobo is 1.15.1 if possible use that one
